# Generated by Django 6.0.5 on 2026-06-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='total_attempts',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='total_made_shots',
        ),
    ]
